### ISSUE TITLE
Unnecessary transitive property paths?

### ISSUE THREAD

**Issue by IgorRodchenkov** [BioPAX/pattern#3]
According to the TransitivePropertyAccessor javadoc (in paxtools-core), - 
"BioPAX has three transitive properties: memberEntityReference, memberEntityFeature, component" (in fact, memberPhysicalEntity - as well), but this module (e.g., in ConBox class) uses not only "PhysicalEntity/memberPhysicalEntity_", "Complex/component_", etc., paths but also:
- "PhysicalEntity/controllerOf/controlled*:Conversion"
- "Control/controlled*:TemplateReaction"
- "Conversion/controlledOf*/controller" (why not simply "Conversion/controlledOf/controller"?)
  etc.

I'm not sure TransitivePropertyAccessor docs is wrong or pattern...

**Comment by ozgunbabur** [comment]
Well, if there are multiple Control objects chained, and they finally reach to a Conversion, then we need this star (*) to traverse the chained Control objects. However, you are right, if there is a loop, like two Control objects are controlling each other, the code may fail. I don't know how the TransitivePropertyEditor was implemented. It probably needs to remember already visited objects.

**Comment by IgorRodchenkov** [comment]
I am looking at the
   TransitivePropertyAccessor.transitiveGet code right now, and will
probably change it there similar to what's done in the AbstractTraverser
(a set of visited biopax objects, to escape infinite loop).

**Comment by IgorRodchenkov** [comment]
Ok, if so, I am closing this issue, and will update the TransitivePropertyAccessor javadoc 
(i.e., there are more than three transitive properties in BioPAX...)

**Comment by ozgunbabur** [comment]
Sounds right.
